<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property \DTS\eBaySDK\PostOrder\Enums\CurrencyCodeEnum $convertedFromCurrency
 * @property \DTS\eBaySDK\PostOrder\Types\Number $convertedFromValue
 * @property \DTS\eBaySDK\PostOrder\Enums\CurrencyCodeEnum $currency
 * @property \DTS\eBaySDK\PostOrder\Types\Number $value
 */
class Amount extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'convertedFromCurrency' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'convertedFromCurrency'
        ],
        'convertedFromValue' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\Number',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'convertedFromValue'
        ],
        'currency' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'currency'
        ],
        'value' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\Number',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'value'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://davidtsadler.com"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
