<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property \DTS\eBaySDK\PostOrder\Types\CountSummaryType[] $countSummary
 * @property \DTS\eBaySDK\PostOrder\Types\PaginationOutput $paginationOutput
 * @property \DTS\eBaySDK\PostOrder\Types\ReturnSummaryType[] $returns
 * @property integer $total
 */
class GetSummaryResponse extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'countSummary' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\CountSummaryType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'countSummary'
        ],
        'paginationOutput' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\PaginationOutput',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationOutput'
        ],
        'returns' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\ReturnSummaryType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'returns'
        ],
        'total' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'total'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://davidtsadler.com"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
